
[development]
[development.database]
pg_port=15100
pg_user="test_user"
pg_pass="test_pass"
pg_db ="test_db"
pg_host="localhost"
max_pool_connections=20

[containerized]
[containerized.database]
pg_port=5432
pg_user="test_user"
pg_pass="test_pass"
pg_db ="test_db"
pg_host="primary_db"
max_pool_connections=20



# From root of project. See utils/aliases.py
[misc]
migrations_folder="/migrations"