version: "3"

services:
  rest:
    build:
      context: "./rest"
      dockerfile: dockerfile
    container_name: deno-deploy
    ports:
      - "15000:15000"
    networks:
      - app-network
    environment:
      - PRODUCTION=1

  primary_db:
    image: postgres:alpine
    restart: always
    container_name: primary_db_prod
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_pass
      - POSTGRES_DB=test_db
      - PGDATA=/var/lib/postgresql/data
    ports:
      - 15100:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data    
    networks: 
      - app-network      





  #grpc:
#
  #soap:

  #postgres:



networks:
  app-network:
    driver: "bridge"
