version: "3"

services:
  frontend:
    build: 
      context: ./frontend
      args:
        environment: prod
    container_name: frontend
    ports:
      - 80:80
    networks:
      - app-network


# Primarily only includes technologies vital to development
