version: "3"

services:
  rest:
    build:
      context: "./rest"
      dockerfile: dockerfile
    container_name: deno-deploy
    ports:
      - "15000:15000"
    networks:
      - app-network
    environment:
      - PRODUCTION=1


  primary_db:
    image: postgres:alpine
    restart: always
    container_name: primary_db_prod
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=${PG_DB}
      - PGDATA=/var/lib/postgresql/data
    ports:
      - 15100:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data    
    networks: 
      - app-network      

  grpc:
    restart: always
    build:
      context: "./grpc"
      dockerfile: dockerfile
    container_name: grpc_prod
    environment:
      - PRODUCTION=1
    ports:
      - 25100:25100
    networks:
      - app-network

    

    
#
  #soap:



networks:
  app-network:
    driver: "bridge"
