[server]
host="localhost"
port=10000

[clients]

[clients.rest]
[clients.rest.mini-proj]
host = "localhost"
port = 10040



[clients.soap]
[clients.soap.mini-proj]
[clients.grpc]
[clients.grpc.mini-proj]