# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: incoming/student.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='incoming/student.proto',
  package='student',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16incoming/student.proto\x12\x07student\"b\n\x14\x43reateStudentRequest\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\x14\n\x0cphone_number\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\"a\n\x13ReadStudentResponse\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\x14\n\x0cphone_number\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\"V\n\x14UpdateStudentRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x32\n\x0bnew_student\x18\x02 \x01(\x0b\x32\x1d.student.CreateStudentRequest\"\"\n\x14\x44\x65leteStudentRequest\x12\n\n\x02id\x18\x01 \x01(\x05\" \n\x12ReadStudentRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x18\n\x16ReadStudentListRequest\"(\n\x15\x43reateStudentResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"M\n\x17ReadStudentListResponse\x12\x32\n\x0cstudent_list\x18\x01 \x03(\x0b\x32\x1c.student.ReadStudentResponse\"(\n\x15UpdateStudentResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"(\n\x15\x44\x65leteStudentResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xa3\x03\n\x07Student\x12P\n\rCreateStudent\x12\x1d.student.CreateStudentRequest\x1a\x1e.student.CreateStudentResponse\"\x00\x12J\n\x0bReadStudent\x12\x1b.student.ReadStudentRequest\x1a\x1c.student.ReadStudentResponse\"\x00\x12P\n\rUpdateStudent\x12\x1d.student.UpdateStudentRequest\x1a\x1e.student.UpdateStudentResponse\"\x00\x12P\n\rDeleteStudent\x12\x1d.student.DeleteStudentRequest\x1a\x1e.student.DeleteStudentResponse\"\x00\x12V\n\x0fReadStudentList\x12\x1f.student.ReadStudentListRequest\x1a .student.ReadStudentListResponse\"\x00\x62\x06proto3'
)




_CREATESTUDENTREQUEST = _descriptor.Descriptor(
  name='CreateStudentRequest',
  full_name='student.CreateStudentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='first_name', full_name='student.CreateStudentRequest.first_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_name', full_name='student.CreateStudentRequest.last_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='phone_number', full_name='student.CreateStudentRequest.phone_number', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='email', full_name='student.CreateStudentRequest.email', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=133,
)


_READSTUDENTRESPONSE = _descriptor.Descriptor(
  name='ReadStudentResponse',
  full_name='student.ReadStudentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='first_name', full_name='student.ReadStudentResponse.first_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_name', full_name='student.ReadStudentResponse.last_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='phone_number', full_name='student.ReadStudentResponse.phone_number', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='email', full_name='student.ReadStudentResponse.email', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=232,
)


_UPDATESTUDENTREQUEST = _descriptor.Descriptor(
  name='UpdateStudentRequest',
  full_name='student.UpdateStudentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='student.UpdateStudentRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='new_student', full_name='student.UpdateStudentRequest.new_student', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=234,
  serialized_end=320,
)


_DELETESTUDENTREQUEST = _descriptor.Descriptor(
  name='DeleteStudentRequest',
  full_name='student.DeleteStudentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='student.DeleteStudentRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=322,
  serialized_end=356,
)


_READSTUDENTREQUEST = _descriptor.Descriptor(
  name='ReadStudentRequest',
  full_name='student.ReadStudentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='student.ReadStudentRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=358,
  serialized_end=390,
)


_READSTUDENTLISTREQUEST = _descriptor.Descriptor(
  name='ReadStudentListRequest',
  full_name='student.ReadStudentListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=392,
  serialized_end=416,
)


_CREATESTUDENTRESPONSE = _descriptor.Descriptor(
  name='CreateStudentResponse',
  full_name='student.CreateStudentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='student.CreateStudentResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=418,
  serialized_end=458,
)


_READSTUDENTLISTRESPONSE = _descriptor.Descriptor(
  name='ReadStudentListResponse',
  full_name='student.ReadStudentListResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='student_list', full_name='student.ReadStudentListResponse.student_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=460,
  serialized_end=537,
)


_UPDATESTUDENTRESPONSE = _descriptor.Descriptor(
  name='UpdateStudentResponse',
  full_name='student.UpdateStudentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='student.UpdateStudentResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=539,
  serialized_end=579,
)


_DELETESTUDENTRESPONSE = _descriptor.Descriptor(
  name='DeleteStudentResponse',
  full_name='student.DeleteStudentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='student.DeleteStudentResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=581,
  serialized_end=621,
)

_UPDATESTUDENTREQUEST.fields_by_name['new_student'].message_type = _CREATESTUDENTREQUEST
_READSTUDENTLISTRESPONSE.fields_by_name['student_list'].message_type = _READSTUDENTRESPONSE
DESCRIPTOR.message_types_by_name['CreateStudentRequest'] = _CREATESTUDENTREQUEST
DESCRIPTOR.message_types_by_name['ReadStudentResponse'] = _READSTUDENTRESPONSE
DESCRIPTOR.message_types_by_name['UpdateStudentRequest'] = _UPDATESTUDENTREQUEST
DESCRIPTOR.message_types_by_name['DeleteStudentRequest'] = _DELETESTUDENTREQUEST
DESCRIPTOR.message_types_by_name['ReadStudentRequest'] = _READSTUDENTREQUEST
DESCRIPTOR.message_types_by_name['ReadStudentListRequest'] = _READSTUDENTLISTREQUEST
DESCRIPTOR.message_types_by_name['CreateStudentResponse'] = _CREATESTUDENTRESPONSE
DESCRIPTOR.message_types_by_name['ReadStudentListResponse'] = _READSTUDENTLISTRESPONSE
DESCRIPTOR.message_types_by_name['UpdateStudentResponse'] = _UPDATESTUDENTRESPONSE
DESCRIPTOR.message_types_by_name['DeleteStudentResponse'] = _DELETESTUDENTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateStudentRequest = _reflection.GeneratedProtocolMessageType('CreateStudentRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATESTUDENTREQUEST,
  '__module__' : 'incoming.student_pb2'
  # @@protoc_insertion_point(class_scope:student.CreateStudentRequest)
  })
_sym_db.RegisterMessage(CreateStudentRequest)

ReadStudentResponse = _reflection.GeneratedProtocolMessageType('ReadStudentResponse', (_message.Message,), {
  'DESCRIPTOR' : _READSTUDENTRESPONSE,
  '__module__' : 'incoming.student_pb2'
  # @@protoc_insertion_point(class_scope:student.ReadStudentResponse)
  })
_sym_db.RegisterMessage(ReadStudentResponse)

UpdateStudentRequest = _reflection.GeneratedProtocolMessageType('UpdateStudentRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATESTUDENTREQUEST,
  '__module__' : 'incoming.student_pb2'
  # @@protoc_insertion_point(class_scope:student.UpdateStudentRequest)
  })
_sym_db.RegisterMessage(UpdateStudentRequest)

DeleteStudentRequest = _reflection.GeneratedProtocolMessageType('DeleteStudentRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETESTUDENTREQUEST,
  '__module__' : 'incoming.student_pb2'
  # @@protoc_insertion_point(class_scope:student.DeleteStudentRequest)
  })
_sym_db.RegisterMessage(DeleteStudentRequest)

ReadStudentRequest = _reflection.GeneratedProtocolMessageType('ReadStudentRequest', (_message.Message,), {
  'DESCRIPTOR' : _READSTUDENTREQUEST,
  '__module__' : 'incoming.student_pb2'
  # @@protoc_insertion_point(class_scope:student.ReadStudentRequest)
  })
_sym_db.RegisterMessage(ReadStudentRequest)

ReadStudentListRequest = _reflection.GeneratedProtocolMessageType('ReadStudentListRequest', (_message.Message,), {
  'DESCRIPTOR' : _READSTUDENTLISTREQUEST,
  '__module__' : 'incoming.student_pb2'
  # @@protoc_insertion_point(class_scope:student.ReadStudentListRequest)
  })
_sym_db.RegisterMessage(ReadStudentListRequest)

CreateStudentResponse = _reflection.GeneratedProtocolMessageType('CreateStudentResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATESTUDENTRESPONSE,
  '__module__' : 'incoming.student_pb2'
  # @@protoc_insertion_point(class_scope:student.CreateStudentResponse)
  })
_sym_db.RegisterMessage(CreateStudentResponse)

ReadStudentListResponse = _reflection.GeneratedProtocolMessageType('ReadStudentListResponse', (_message.Message,), {
  'DESCRIPTOR' : _READSTUDENTLISTRESPONSE,
  '__module__' : 'incoming.student_pb2'
  # @@protoc_insertion_point(class_scope:student.ReadStudentListResponse)
  })
_sym_db.RegisterMessage(ReadStudentListResponse)

UpdateStudentResponse = _reflection.GeneratedProtocolMessageType('UpdateStudentResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPDATESTUDENTRESPONSE,
  '__module__' : 'incoming.student_pb2'
  # @@protoc_insertion_point(class_scope:student.UpdateStudentResponse)
  })
_sym_db.RegisterMessage(UpdateStudentResponse)

DeleteStudentResponse = _reflection.GeneratedProtocolMessageType('DeleteStudentResponse', (_message.Message,), {
  'DESCRIPTOR' : _DELETESTUDENTRESPONSE,
  '__module__' : 'incoming.student_pb2'
  # @@protoc_insertion_point(class_scope:student.DeleteStudentResponse)
  })
_sym_db.RegisterMessage(DeleteStudentResponse)



_STUDENT = _descriptor.ServiceDescriptor(
  name='Student',
  full_name='student.Student',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=624,
  serialized_end=1043,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateStudent',
    full_name='student.Student.CreateStudent',
    index=0,
    containing_service=None,
    input_type=_CREATESTUDENTREQUEST,
    output_type=_CREATESTUDENTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ReadStudent',
    full_name='student.Student.ReadStudent',
    index=1,
    containing_service=None,
    input_type=_READSTUDENTREQUEST,
    output_type=_READSTUDENTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateStudent',
    full_name='student.Student.UpdateStudent',
    index=2,
    containing_service=None,
    input_type=_UPDATESTUDENTREQUEST,
    output_type=_UPDATESTUDENTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteStudent',
    full_name='student.Student.DeleteStudent',
    index=3,
    containing_service=None,
    input_type=_DELETESTUDENTREQUEST,
    output_type=_DELETESTUDENTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ReadStudentList',
    full_name='student.Student.ReadStudentList',
    index=4,
    containing_service=None,
    input_type=_READSTUDENTLISTREQUEST,
    output_type=_READSTUDENTLISTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_STUDENT)

DESCRIPTOR.services_by_name['Student'] = _STUDENT

# @@protoc_insertion_point(module_scope)
