# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: outgoing/student_out.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='outgoing/student_out.proto',
  package='student_out',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1aoutgoing/student_out.proto\x12\x0bstudent_out\"b\n\x14\x43reateStudentRequest\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\x14\n\x0cphone_number\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\"a\n\x13ReadStudentResponse\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\x14\n\x0cphone_number\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\"Z\n\x14UpdateStudentRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x36\n\x0bnew_student\x18\x02 \x01(\x0b\x32!.student_out.CreateStudentRequest\"\"\n\x14\x44\x65leteStudentRequest\x12\n\n\x02id\x18\x01 \x01(\x05\" \n\x12ReadStudentRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x18\n\x16ReadStudentListRequest\"(\n\x15\x43reateStudentResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"Q\n\x17ReadStudentListResponse\x12\x36\n\x0cstudent_list\x18\x01 \x03(\x0b\x32 .student_out.ReadStudentResponse\"(\n\x15UpdateStudentResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"(\n\x15\x44\x65leteStudentResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xce\x03\n\nStudentOut\x12X\n\rCreateStudent\x12!.student_out.CreateStudentRequest\x1a\".student_out.CreateStudentResponse\"\x00\x12R\n\x0bReadStudent\x12\x1f.student_out.ReadStudentRequest\x1a .student_out.ReadStudentResponse\"\x00\x12X\n\rUpdateStudent\x12!.student_out.UpdateStudentRequest\x1a\".student_out.UpdateStudentResponse\"\x00\x12X\n\rDeleteStudent\x12!.student_out.DeleteStudentRequest\x1a\".student_out.DeleteStudentResponse\"\x00\x12^\n\x0fReadStudentList\x12#.student_out.ReadStudentListRequest\x1a$.student_out.ReadStudentListResponse\"\x00\x62\x06proto3'
)




_CREATESTUDENTREQUEST = _descriptor.Descriptor(
  name='CreateStudentRequest',
  full_name='student_out.CreateStudentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='first_name', full_name='student_out.CreateStudentRequest.first_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_name', full_name='student_out.CreateStudentRequest.last_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='phone_number', full_name='student_out.CreateStudentRequest.phone_number', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='email', full_name='student_out.CreateStudentRequest.email', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=141,
)


_READSTUDENTRESPONSE = _descriptor.Descriptor(
  name='ReadStudentResponse',
  full_name='student_out.ReadStudentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='first_name', full_name='student_out.ReadStudentResponse.first_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_name', full_name='student_out.ReadStudentResponse.last_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='phone_number', full_name='student_out.ReadStudentResponse.phone_number', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='email', full_name='student_out.ReadStudentResponse.email', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=240,
)


_UPDATESTUDENTREQUEST = _descriptor.Descriptor(
  name='UpdateStudentRequest',
  full_name='student_out.UpdateStudentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='student_out.UpdateStudentRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='new_student', full_name='student_out.UpdateStudentRequest.new_student', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=242,
  serialized_end=332,
)


_DELETESTUDENTREQUEST = _descriptor.Descriptor(
  name='DeleteStudentRequest',
  full_name='student_out.DeleteStudentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='student_out.DeleteStudentRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=334,
  serialized_end=368,
)


_READSTUDENTREQUEST = _descriptor.Descriptor(
  name='ReadStudentRequest',
  full_name='student_out.ReadStudentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='student_out.ReadStudentRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=370,
  serialized_end=402,
)


_READSTUDENTLISTREQUEST = _descriptor.Descriptor(
  name='ReadStudentListRequest',
  full_name='student_out.ReadStudentListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=404,
  serialized_end=428,
)


_CREATESTUDENTRESPONSE = _descriptor.Descriptor(
  name='CreateStudentResponse',
  full_name='student_out.CreateStudentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='student_out.CreateStudentResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=430,
  serialized_end=470,
)


_READSTUDENTLISTRESPONSE = _descriptor.Descriptor(
  name='ReadStudentListResponse',
  full_name='student_out.ReadStudentListResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='student_list', full_name='student_out.ReadStudentListResponse.student_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=472,
  serialized_end=553,
)


_UPDATESTUDENTRESPONSE = _descriptor.Descriptor(
  name='UpdateStudentResponse',
  full_name='student_out.UpdateStudentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='student_out.UpdateStudentResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=555,
  serialized_end=595,
)


_DELETESTUDENTRESPONSE = _descriptor.Descriptor(
  name='DeleteStudentResponse',
  full_name='student_out.DeleteStudentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='student_out.DeleteStudentResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=597,
  serialized_end=637,
)

_UPDATESTUDENTREQUEST.fields_by_name['new_student'].message_type = _CREATESTUDENTREQUEST
_READSTUDENTLISTRESPONSE.fields_by_name['student_list'].message_type = _READSTUDENTRESPONSE
DESCRIPTOR.message_types_by_name['CreateStudentRequest'] = _CREATESTUDENTREQUEST
DESCRIPTOR.message_types_by_name['ReadStudentResponse'] = _READSTUDENTRESPONSE
DESCRIPTOR.message_types_by_name['UpdateStudentRequest'] = _UPDATESTUDENTREQUEST
DESCRIPTOR.message_types_by_name['DeleteStudentRequest'] = _DELETESTUDENTREQUEST
DESCRIPTOR.message_types_by_name['ReadStudentRequest'] = _READSTUDENTREQUEST
DESCRIPTOR.message_types_by_name['ReadStudentListRequest'] = _READSTUDENTLISTREQUEST
DESCRIPTOR.message_types_by_name['CreateStudentResponse'] = _CREATESTUDENTRESPONSE
DESCRIPTOR.message_types_by_name['ReadStudentListResponse'] = _READSTUDENTLISTRESPONSE
DESCRIPTOR.message_types_by_name['UpdateStudentResponse'] = _UPDATESTUDENTRESPONSE
DESCRIPTOR.message_types_by_name['DeleteStudentResponse'] = _DELETESTUDENTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateStudentRequest = _reflection.GeneratedProtocolMessageType('CreateStudentRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATESTUDENTREQUEST,
  '__module__' : 'outgoing.student_out_pb2'
  # @@protoc_insertion_point(class_scope:student_out.CreateStudentRequest)
  })
_sym_db.RegisterMessage(CreateStudentRequest)

ReadStudentResponse = _reflection.GeneratedProtocolMessageType('ReadStudentResponse', (_message.Message,), {
  'DESCRIPTOR' : _READSTUDENTRESPONSE,
  '__module__' : 'outgoing.student_out_pb2'
  # @@protoc_insertion_point(class_scope:student_out.ReadStudentResponse)
  })
_sym_db.RegisterMessage(ReadStudentResponse)

UpdateStudentRequest = _reflection.GeneratedProtocolMessageType('UpdateStudentRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATESTUDENTREQUEST,
  '__module__' : 'outgoing.student_out_pb2'
  # @@protoc_insertion_point(class_scope:student_out.UpdateStudentRequest)
  })
_sym_db.RegisterMessage(UpdateStudentRequest)

DeleteStudentRequest = _reflection.GeneratedProtocolMessageType('DeleteStudentRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETESTUDENTREQUEST,
  '__module__' : 'outgoing.student_out_pb2'
  # @@protoc_insertion_point(class_scope:student_out.DeleteStudentRequest)
  })
_sym_db.RegisterMessage(DeleteStudentRequest)

ReadStudentRequest = _reflection.GeneratedProtocolMessageType('ReadStudentRequest', (_message.Message,), {
  'DESCRIPTOR' : _READSTUDENTREQUEST,
  '__module__' : 'outgoing.student_out_pb2'
  # @@protoc_insertion_point(class_scope:student_out.ReadStudentRequest)
  })
_sym_db.RegisterMessage(ReadStudentRequest)

ReadStudentListRequest = _reflection.GeneratedProtocolMessageType('ReadStudentListRequest', (_message.Message,), {
  'DESCRIPTOR' : _READSTUDENTLISTREQUEST,
  '__module__' : 'outgoing.student_out_pb2'
  # @@protoc_insertion_point(class_scope:student_out.ReadStudentListRequest)
  })
_sym_db.RegisterMessage(ReadStudentListRequest)

CreateStudentResponse = _reflection.GeneratedProtocolMessageType('CreateStudentResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATESTUDENTRESPONSE,
  '__module__' : 'outgoing.student_out_pb2'
  # @@protoc_insertion_point(class_scope:student_out.CreateStudentResponse)
  })
_sym_db.RegisterMessage(CreateStudentResponse)

ReadStudentListResponse = _reflection.GeneratedProtocolMessageType('ReadStudentListResponse', (_message.Message,), {
  'DESCRIPTOR' : _READSTUDENTLISTRESPONSE,
  '__module__' : 'outgoing.student_out_pb2'
  # @@protoc_insertion_point(class_scope:student_out.ReadStudentListResponse)
  })
_sym_db.RegisterMessage(ReadStudentListResponse)

UpdateStudentResponse = _reflection.GeneratedProtocolMessageType('UpdateStudentResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPDATESTUDENTRESPONSE,
  '__module__' : 'outgoing.student_out_pb2'
  # @@protoc_insertion_point(class_scope:student_out.UpdateStudentResponse)
  })
_sym_db.RegisterMessage(UpdateStudentResponse)

DeleteStudentResponse = _reflection.GeneratedProtocolMessageType('DeleteStudentResponse', (_message.Message,), {
  'DESCRIPTOR' : _DELETESTUDENTRESPONSE,
  '__module__' : 'outgoing.student_out_pb2'
  # @@protoc_insertion_point(class_scope:student_out.DeleteStudentResponse)
  })
_sym_db.RegisterMessage(DeleteStudentResponse)



_STUDENTOUT = _descriptor.ServiceDescriptor(
  name='StudentOut',
  full_name='student_out.StudentOut',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=640,
  serialized_end=1102,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateStudent',
    full_name='student_out.StudentOut.CreateStudent',
    index=0,
    containing_service=None,
    input_type=_CREATESTUDENTREQUEST,
    output_type=_CREATESTUDENTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ReadStudent',
    full_name='student_out.StudentOut.ReadStudent',
    index=1,
    containing_service=None,
    input_type=_READSTUDENTREQUEST,
    output_type=_READSTUDENTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateStudent',
    full_name='student_out.StudentOut.UpdateStudent',
    index=2,
    containing_service=None,
    input_type=_UPDATESTUDENTREQUEST,
    output_type=_UPDATESTUDENTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteStudent',
    full_name='student_out.StudentOut.DeleteStudent',
    index=3,
    containing_service=None,
    input_type=_DELETESTUDENTREQUEST,
    output_type=_DELETESTUDENTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ReadStudentList',
    full_name='student_out.StudentOut.ReadStudentList',
    index=4,
    containing_service=None,
    input_type=_READSTUDENTLISTREQUEST,
    output_type=_READSTUDENTLISTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_STUDENTOUT)

DESCRIPTOR.services_by_name['StudentOut'] = _STUDENTOUT

# @@protoc_insertion_point(module_scope)
