CREATE TABLE IF NOT EXISTS grades_students(
    grade_id INTEGER REFERENCES grades(id) ON UPDATE CASCADE ON DELETE CASCADE,
    student_id INTEGER REFERENCES students(id) ON UPDATE CASCADE ON DELETE CASCADE
);