CREATE TABLE IF NOT EXISTS grades_students(
    grade_id INTEGER REFERENCES grade(id) ON UPDATE CASCADE ON DELETE CASCADE,
    student_id INTEGER REFERENCES teacher(id) ON UPDATE CASCADE ON DELETE CASCADE
);