
[production]

[production.server]
port=25100
host="0.0.0.0"

[production.database]
pg_port=13291
pg_user="test_user"
pg_pass="test_pass"
pg_db ="test_db"
pg_host="localhost"

[development]

[development.server]
port=25100
host="0.0.0.0"

[development.database]
pg_port=13291
pg_user="test_user"
pg_pass="test_pass"
pg_db ="test_db"
pg_host="localhost"