FROM rust:1.55

# Postgres
RUN apt-get install libpq-dev -y
RUN apt-get update

WORKDIR /usr/src/backend
COPY . .

#RUN cargo install --path .
RUN cargo b
EXPOSE 25100

CMD ["cargo","r","--bin","mini-proj-server"]
