FROM rust:1.55

# Postgres
RUN apt-get install libpq-dev -y
RUN apt-get update

WORKDIR /usr/src/backend
COPY . .

EXPOSE 13000
#RUN cargo install --path .
RUN rustup component add rustfmt
RUN cargo b --release

CMD ["cargo","r","--bin","mini-proj-server"]
